services:
  app:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - PORT=8080
      - APP_NAME=search-service
      - APP_ENV=production
      - MAX_RETRY_COUNT=3
      - RETRY_BACKOFF=200
      - REQUEST_LIMITER_TTL=60s
      - REQUEST_LIMITER_MAX=10
    networks:
      - bookcabin_network
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - bookcabin_network

networks:
  bookcabin_network:
    driver: bridge